# Generated by Django 3.2.3 on 2021-05-14 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_follow_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Выберите группу!', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.group', verbose_name='Группа'),
        ),
    ]
